# Generated by Django 2.2.4 on 2020-08-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=200, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Iva')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Descuento')),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(default='', upload_to='articulo/%Y/%m/%d/')),
                ('elim', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('fechaingreso', models.DateTimeField(blank=True, default='', verbose_name='Fecha Ingreso')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Stock')),
                ('fechasalida', models.DateTimeField(blank=True, default='', verbose_name='Fecha Ingreso')),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Iva')),
                ('preciocompra', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Precio Compra')),
                ('precioventa', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Precio Venta')),
                ('user', models.IntegerField(default=0, verbose_name='Usuario')),
                ('userfecha', models.DateTimeField(default='', verbose_name='Fechausuario')),
                ('usermodificardor', models.IntegerField(default=0, verbose_name='Descuento')),
                ('userfechamodificador', models.DateTimeField(default='', verbose_name='Fechamodificada')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=200, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True)),
                ('elim', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Articulo')),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Kardex')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['articulo'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Marca'),
        ),
    ]
