# Generated by Django 2.2.4 on 2020-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacompra', models.DateTimeField(blank=True, default='', verbose_name='Fecha')),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Iva')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Total')),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Descuento')),
                ('userfecha', models.DateTimeField(default='', verbose_name='Fechausuario')),
                ('usermodificardor', models.IntegerField(default=0, verbose_name='Fechausuariomodifcador')),
                ('userfechamodificador', models.DateTimeField(default='', verbose_name='Fechamodificada')),
                ('status', models.BooleanField(default=True)),
                ('tipocomprobante', models.IntegerField(default=0, verbose_name='Tipo de comrobante')),
                ('impuesto', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Total')),
                ('preciototal', models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Precio Total')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(default='', max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='Telefono')),
                ('ced_ruc', models.CharField(default='', max_length=14, verbose_name='Cedula o Ruc')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Email')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
